-- Module 1: browser telemetry foundation.
--
-- Four tables, matching the four things the extension actually reports. Later
-- modules add screenshots, OCR results and AI analyses; they are not created
-- here, because a table with no writer is just a guess about the future.

-- ---------------------------------------------------------------------------
-- users
--
-- Not accounts. Module 1 has no sign-in: a user row is one browser profile,
-- identified by a random id the extension generates on install. It holds
-- nothing about a person, and exists so sessions from the same browser can be
-- grouped and so row-level security has something to key on later.
-- ---------------------------------------------------------------------------
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  installation_id text not null unique,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- sessions
--
-- A stretch of continuous browsing. The id is generated by the extension, so a
-- session survives the service worker being killed and restarted.
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  id uuid primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz,
  created_at timestamptz not null default now(),

  constraint sessions_end_after_start check (ended_at is null or ended_at >= started_at)
);

create index if not exists sessions_user_started_idx
  on public.sessions (user_id, started_at desc);

-- ---------------------------------------------------------------------------
-- tabs
--
-- Chrome's tab ids are only unique within a browser run, so they cannot be a
-- primary key. The natural key is (session, browser tab id).
-- ---------------------------------------------------------------------------
create table if not exists public.tabs (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions (id) on delete cascade,
  browser_tab_id integer not null,
  window_id integer,
  last_url text,
  last_title text,
  opened_at timestamptz,
  closed_at timestamptz,

  unique (session_id, browser_tab_id)
);

create index if not exists tabs_session_idx on public.tabs (session_id);

-- ---------------------------------------------------------------------------
-- events
--
-- The id is generated by the extension and is the primary key, which is what
-- makes ingest idempotent: a batch re-sent after a lost response conflicts on
-- insert and is skipped rather than duplicated.
-- ---------------------------------------------------------------------------
create table if not exists public.events (
  id uuid primary key,
  session_id uuid not null references public.sessions (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  type text not null,
  occurred_at timestamptz not null,
  url text,
  domain text,
  title text,
  browser_tab_id integer,
  window_id integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- The dashboard's default view: this user's most recent activity.
create index if not exists events_user_occurred_idx
  on public.events (user_id, occurred_at desc);

-- Session explorer: everything that happened in one session, in order.
create index if not exists events_session_occurred_idx
  on public.events (session_id, occurred_at desc);

-- Filtering by site and by kind of activity.
create index if not exists events_domain_idx on public.events (domain)
  where domain is not null;
create index if not exists events_type_idx on public.events (type);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Enabled with no policies attached, which denies every request that arrives
-- with an anon or authenticated key. Only the service role bypasses RLS, and
-- that key lives solely on the backend.
--
-- This is deliberately restrictive. Module 1 has no end-user authentication, so
-- there is no honest policy to write yet: any policy permissive enough to let a
-- browser client read would let it read everyone's browsing history. When
-- per-user auth arrives, policies keyed on auth.uid() replace this comment.
-- ---------------------------------------------------------------------------
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.tabs enable row level security;
alter table public.events enable row level security;
