-- Module 2: visual understanding.
--
-- Four tables added on top of the Module 1 schema, none of which alter it. The
-- telemetry foundation keeps working unchanged if none of this is ever
-- populated, which is the point: AI is an enhancement layer, not a dependency.

-- ---------------------------------------------------------------------------
-- screenshots
--
-- Metadata only. The image bytes live in object storage; PostgreSQL holds the
-- path to them. Storing a few hundred kilobytes per row would bloat every
-- query that never wanted the image.
--
-- The id is generated by the extension, like event ids, so an upload retried
-- after a lost response conflicts rather than duplicating.
-- ---------------------------------------------------------------------------
create table if not exists public.screenshots (
  id uuid primary key,
  session_id uuid not null references public.sessions (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,

  storage_bucket text not null,
  storage_path text not null,

  captured_at timestamptz not null,
  format text not null,
  width integer not null,
  height integer not null,
  byte_size integer not null,
  trigger text not null,

  page_url text,
  domain text,
  page_title text,
  browser_tab_id integer,

  -- Drives the analysis worker's queue. `attempts` bounds retries so one
  -- permanently unreadable image cannot be picked up forever.
  analysis_status text not null default 'pending',
  analysis_attempts integer not null default 0,
  analysis_error text,

  created_at timestamptz not null default now(),

  constraint screenshots_status_known
    check (analysis_status in ('pending', 'processing', 'completed', 'failed')),
  constraint screenshots_trigger_known check (trigger in ('manual', 'navigation'))
);

-- The worker's only query: the oldest work still waiting.
create index if not exists screenshots_pending_idx
  on public.screenshots (analysis_status, captured_at)
  where analysis_status in ('pending', 'processing');

create index if not exists screenshots_session_captured_idx
  on public.screenshots (session_id, captured_at desc);

create index if not exists screenshots_user_captured_idx
  on public.screenshots (user_id, captured_at desc);

-- ---------------------------------------------------------------------------
-- ocr_results
--
-- One per screenshot. Separate from the screenshot row because extracted text
-- can be large and is rarely wanted alongside a list of captures.
-- ---------------------------------------------------------------------------
create table if not exists public.ocr_results (
  id uuid primary key default gen_random_uuid(),
  screenshot_id uuid not null unique references public.screenshots (id) on delete cascade,

  text text not null,
  word_count integer not null default 0,
  -- Null when the engine reported no per-word confidence at all.
  mean_confidence numeric(4, 3),
  engine text not null,
  duration_ms integer not null default 0,

  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- ai_analyses
--
-- Structured understanding produced from a screenshot and its OCR text.
--
-- Not unique per screenshot: re-running with a different provider or model is a
-- new analysis, and comparing them is worth being able to do. The provider and
-- model are recorded on every row for the same reason.
--
-- `raw` keeps what the model actually returned, so a disagreement between the
-- stored fields and the model's output can be settled by looking.
-- ---------------------------------------------------------------------------
create table if not exists public.ai_analyses (
  id uuid primary key default gen_random_uuid(),
  screenshot_id uuid not null references public.screenshots (id) on delete cascade,
  session_id uuid not null references public.sessions (id) on delete cascade,

  provider text not null,
  model text not null,

  page_type text not null,
  category text not null,
  purpose text not null,
  important_elements jsonb not null default '[]'::jsonb,
  visible_content_summary text,

  user_intent text not null,
  current_task text not null,
  activity_category text not null,
  summary text not null,
  confidence numeric(4, 3),

  raw jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_analyses_screenshot_idx on public.ai_analyses (screenshot_id);
create index if not exists ai_analyses_session_idx on public.ai_analyses (session_id, created_at desc);
create index if not exists ai_analyses_category_idx on public.ai_analyses (activity_category);

-- ---------------------------------------------------------------------------
-- timeline_activities
--
-- The readable layer over raw events: "Researching a GitHub issue" rather than
-- CLICK, SCROLL, SCROLL, NAVIGATION.
--
-- Regenerated wholesale for a session rather than amended, because an activity's
-- boundaries can move as later events arrive — a gap that looked like the end of
-- an activity becomes a pause in the middle of one.
--
-- `source` records whether a model wrote the description or it was assembled
-- from the events, since the two are not equally trustworthy and the timeline
-- must work with no AI configured.
-- ---------------------------------------------------------------------------
create table if not exists public.timeline_activities (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,

  started_at timestamptz not null,
  ended_at timestamptz not null,

  title text not null,
  description text,
  category text not null,
  domains text[] not null default '{}',
  event_count integer not null default 0,
  source text not null,

  created_at timestamptz not null default now(),

  constraint timeline_end_after_start check (ended_at >= started_at),
  constraint timeline_source_known check (source in ('ai', 'derived'))
);

create index if not exists timeline_session_started_idx
  on public.timeline_activities (session_id, started_at);

create index if not exists timeline_user_started_idx
  on public.timeline_activities (user_id, started_at desc);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Same posture as Module 1: enabled with no policies, so only the service role
-- reaches these tables. Screenshots and their extracted text are the most
-- sensitive data the system holds, which makes this more important here, not
-- less.
-- ---------------------------------------------------------------------------
alter table public.screenshots enable row level security;
alter table public.ocr_results enable row level security;
alter table public.ai_analyses enable row level security;
alter table public.timeline_activities enable row level security;
