import { z } from 'zod';
import { EVENT_LIMITS } from './limits.js';
import { storedAnalysisSchema } from './vision.js';

const isoTimestamp = z.iso.datetime({ offset: true });

/** How far a screenshot has got through the analysis pipeline. */
export const ANALYSIS_STATUSES = ['pending', 'processing', 'completed', 'failed'] as const;
export const analysisStatusSchema = z.enum(ANALYSIS_STATUSES);
export type AnalysisStatus = z.infer<typeof analysisStatusSchema>;

/** Only formats a browser can produce and a vision model will accept. */
export const screenshotFormatSchema = z.enum(['jpeg', 'png']);
export type ScreenshotFormat = z.infer<typeof screenshotFormatSchema>;

/**
 * Body of `POST /api/screenshots`.
 *
 * Base64 rather than multipart: a single capture is a few hundred kilobytes,
 * the extension already has it as a data URL, and one JSON path is easier to
 * validate than two content types. The route caps the body separately from the
 * event route, which is bounded far more tightly.
 */
export const uploadScreenshotRequestSchema = z.object({
  installationId: z.uuid(),
  sessionId: z.uuid(),
  /** Generated by the extension, so the upload is idempotent under retry. */
  screenshotId: z.uuid(),
  capturedAt: isoTimestamp,
  format: screenshotFormatSchema,
  /** Raw base64, without the `data:image/...;base64,` prefix. */
  imageBase64: z.string().min(1),
  width: z.number().int().positive().max(20000),
  height: z.number().int().positive().max(20000),
  pageUrl: z.string().max(EVENT_LIMITS.urlMaxLength).optional(),
  domain: z.string().max(255).optional(),
  pageTitle: z.string().max(EVENT_LIMITS.titleMaxLength).optional(),
  tabId: z.number().int().optional(),
  /** Why this capture happened, for auditing the capture policy. */
  trigger: z.enum(['manual', 'navigation']),
});

export type UploadScreenshotRequest = z.infer<typeof uploadScreenshotRequestSchema>;

export const uploadScreenshotResponseSchema = z.object({
  screenshotId: z.uuid(),
  /** False when this id had already been stored, so the client can stop retrying. */
  stored: z.boolean(),
  analysisStatus: analysisStatusSchema,
});

export type UploadScreenshotResponse = z.infer<typeof uploadScreenshotResponseSchema>;

/** OCR output for one screenshot. */
export const ocrResultSchema = z.object({
  text: z.string(),
  wordCount: z.number().int().nonnegative(),
  /** Mean per-word confidence, 0–1. Low values usually mean a dense screenshot. */
  meanConfidence: z.number().min(0).max(1).nullable(),
  engine: z.string(),
  durationMs: z.number().int().nonnegative(),
});

export type OcrResult = z.infer<typeof ocrResultSchema>;

/** A screenshot and everything derived from it, as the API returns it. */
export const screenshotSchema = z.object({
  id: z.uuid(),
  sessionId: z.uuid(),
  capturedAt: isoTimestamp,
  format: screenshotFormatSchema,
  width: z.number().int(),
  height: z.number().int(),
  byteSize: z.number().int(),
  trigger: z.enum(['manual', 'navigation']),
  pageUrl: z.string().nullable(),
  domain: z.string().nullable(),
  pageTitle: z.string().nullable(),
  analysisStatus: analysisStatusSchema,
  /** Why the last analysis attempt failed, if it did. */
  analysisError: z.string().nullable(),
  ocr: ocrResultSchema.nullable(),
  analysis: storedAnalysisSchema.nullable(),
});

export type Screenshot = z.infer<typeof screenshotSchema>;

export const listScreenshotsQuerySchema = z.object({
  sessionId: z.uuid().optional(),
  status: analysisStatusSchema.optional(),
  limit: z.coerce.number().int().min(1).max(100).default(30),
  offset: z.coerce.number().int().min(0).default(0),
});

export type ListScreenshotsQuery = z.infer<typeof listScreenshotsQuerySchema>;

export const listScreenshotsResponseSchema = z.object({
  screenshots: z.array(screenshotSchema),
  total: z.number().int().nonnegative(),
});

export type ListScreenshotsResponse = z.infer<typeof listScreenshotsResponseSchema>;

/**
 * Ceilings on visual capture.
 *
 * Enforced in the extension so the traffic is never generated, and again on the
 * server so a modified client cannot bypass them.
 */
export const SCREENSHOT_LIMITS = {
  /** A 4K JPEG at the quality used sits far below this. */
  maxBytes: 6 * 1024 * 1024,
  /** Minimum gap between automatic captures in one tab. */
  minAutoIntervalMs: 45_000,
  /** Ceiling per session, so a long browsing day cannot fill storage. */
  maxPerSession: 200,
} as const;
